C:\PROGRA~1\NVIDIA~2\CUDA\v10.2\bin\nvcc.exe ^
  -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA ^
  -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP ^
  -I.\ -Idependencies\cub ^
  -ftemplate-backtrace-limit 64 ^
  -gencode arch=compute_75,code=sm_75 ^
  -Xcompiler=/WX -Xcompiler=/wd4244 -Xcompiler=/wd4267 -Xcompiler=/wd4800 ^
  -Xcompiler=/wd4146 -Xcompiler=/wd4494 -Xcompiler=/bigobj ^
  -Werror all-warnings -Xcudafe --display_error_number ^
  -Xcompiler="-MD -O2 -Ob2" ^
  -DNDEBUG ^
  -x cu ^
  -c repro-1090.cu && ^
C:\PROGRA~1\NVIDIA~2\CUDA\v10.2\bin\nvcc.exe ^
  -ccbin=C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\cl.exe ^
  -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA ^
  -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP ^
  -I.\ -Idependencies\cub ^
  -ftemplate-backtrace-limit 64 ^
  -gencode arch=compute_75,code=sm_75 ^
  -Xcompiler=/WX -Xcompiler=/wd4244 -Xcompiler=/wd4267 -Xcompiler=/wd4800 ^
  -Xcompiler=/wd4146 -Xcompiler=/wd4494 -Xcompiler=/bigobj ^
  -Werror all-warnings -Xcudafe --display_error_number ^
  -Xcompiler="-MD -O2 -Ob2" ^
  -DNDEBUG ^
  -x cu ^
  -M repro-1090.cu ^
  -o repro-1090.cu.deps
