komrade: komrade::device_ptr< T > Struct Template Reference
komrade::device_ptr< T > Struct Template Reference
[Memory Management Classes]
#include <device_ptr.h>
Public Types
typedef
komrade::random_access_device_iterator_tag iterator_category
typedef T value_type
typedef ptrdiff_t difference_type
typedef device_ptr pointer
typedef device_reference< T > reference
Public Member Functions
__host__ __device__ device_ptr (void)
template<class Y>
__host__ __device__ device_ptr (Y *ptr)
__host__ __device__ device_ptr (const device_ptr< typename detail::remove_const< value_type >::type > &ptr)
template<typename U>
__host__ __device__ operator device_ptr< U > (void) const
__host__ __device__ device_ptr operator+ (const difference_type &rhs) const
__host__ __device__ device_ptr operator- (const difference_type &rhs) const
__host__ __device__ device_ptr & operator++ (void)
__host__ __device__ device_ptr operator++ (int)
__host__ __device__ device_ptr & operator-- (void)
__host__ __device__ device_ptr operator-- (int)
__host__ __device__ device_ptr & operator+= (difference_type rhs)
__host__ __device__ device_ptr & operator-= (difference_type rhs)
__host__ __device__ difference_type operator- (const device_ptr &rhs) const
__host__ __device__ reference operator[] (const difference_type &i) const
__host__ __device__ reference operator* (void) const
__host__ __device__ value_type * get (void) const
Friends
struct komrade::detail::device_dereferenceable_iterator_traits< komrade::device_ptr< T > >
struct komrade::detail::make_device_dereferenceable< komrade::device_ptr< T > >
Detailed Description
template<typename T>
struct komrade::device_ptr< T >
device_ptr stores a pointer to an object allocated in device memory. This type provides type safety when dispatching standard algorithms on ranges resident in device memory.
device_ptr can be created with the functions device_malloc, device_new, or device_pointer_cast, or by explicitly calling its constructor with a raw pointer.
The raw pointer encapsulated by a device_ptr may be obtained by either its get method or the device_pointer_cast free function.
Note:
device_ptr is not a smart pointer; it is the programmer's responsibility to deallocate memory pointed to by device_ptr.
See also:
device_malloc
device_new
device_pointer_cast
raw_pointer_cast
Constructor & Destructor Documentation
template<typename T> __host__ __device__ komrade::device_ptr< T >::device_ptr (void) [inline]
device_ptr's null constructor initializes its raw pointer to 0.
Referenced by komrade::device_ptr< T >::operator+(), and komrade::device_ptr< T >::operator-().
template<typename T> template<class Y> __host__ __device__ komrade::device_ptr< T >::device_ptr (Y * ptr) [inline, explicit]
device_ptr's copy constructor is templated to allow copying to a const T * from a T *.
Parameters:
ptr A raw pointer to copy from, presumed to point to a location in device memory.
template<typename T> __host__ __device__ komrade::device_ptr< T >::device_ptr (const device_ptr< typename detail::remove_const< value_type >::type > & ptr) [inline]
device_ptr's copy constructor allows copying from another device_ptr with related type.
Parameters:
ptr The device_ptr to copy from.
Member Function Documentation
template<typename T> template<typename U> __host__ __device__ komrade::device_ptr< T >::operator device_ptr< U > (void) const [inline]
device_ptr's conversion operator allows conversion to device_ptr<U> with U related to T. For example, device_ptr<int> may be converted to device_ptr<void>.
Returns:
A copy of this device_ptr, converted to device_ptr<U>.
template<typename T> __host__ __device__ device_ptr komrade::device_ptr< T >::operator+ (const difference_type & rhs) const [inline]
Returns a device_ptr whose raw pointer is equal to this device_ptr's raw pointer plus the given sum.
Parameters:
rhs The sum to add to this device_ptr's raw pointer.
Returns:
device_ptr(mPtr + rhs).
References komrade::device_ptr< T >::device_ptr().
template<typename T> __host__ __device__ device_ptr komrade::device_ptr< T >::operator- (const difference_type & rhs) const [inline]
Returns a device_ptr whose raw pointer is equal to this device_ptr's raw pointer minus the given difference.
Parameters:
rhs The difference to subtract to this device_ptr's raw pointer.
Returns:
device_ptr(mPtr - rhs).
References komrade::device_ptr< T >::device_ptr().
template<typename T> __host__ __device__ device_ptr& komrade::device_ptr< T >::operator++ (void) [inline]
The pre-increment operator increments this device_ptr's raw pointer and then returns a reference to this device_ptr
Returns:
*this
template<typename T> __host__ __device__ device_ptr komrade::device_ptr< T >::operator++ (int) [inline]
The post-increment operator copies this device_ptr, increments the copy, and then returns the copy.
Returns:
A copy of this device_ptr after being incremented.
References komrade::copy().
template<typename T> __host__ __device__ device_ptr& komrade::device_ptr< T >::operator-- (void) [inline]
The pre-decrement operator decrements this device_ptr's raw pointer and then returns a reference to this device_ptr
Returns:
*this
template<typename T> __host__ __device__ device_ptr komrade::device_ptr< T >::operator-- (int) [inline]
The post-decrement operator copies this device_ptr, decrements the copy, and then returns the copy.
Returns:
A copy of this device_ptr after being decremented.
References komrade::copy().
template<typename T> __host__ __device__ device_ptr& komrade::device_ptr< T >::operator+= (difference_type rhs) [inline]
The addition assignment operator adds the given sum to this device_ptr's raw pointer and returns this device_ptr by reference.
Parameters:
rhs The sum to add to this device_ptr's raw pointer.
Returns:
*this
template<typename T> __host__ __device__ device_ptr& komrade::device_ptr< T >::operator-= (difference_type rhs) [inline]
The subtraction assignment operator subtracts the given difference from this device_ptr's raw pointer and returns this device_ptr by reference.
Parameters:
rhs The difference to subtract from this device_ptr's raw pointer.
Returns:
*this
template<typename T> __host__ __device__ difference_type komrade::device_ptr< T >::operator- (const device_ptr< T > & rhs) const [inline]
The difference operator returns the difference between this device_ptr's raw pointer and that of another.
Parameters:
rhs The device_ptr to subtract from this device_ptr.
Returns:
The difference between this device_ptr's raw pointer and rhs's raw pointer.
References komrade::device_ptr< T >::mPtr.
template<typename T> __host__ __device__ reference komrade::device_ptr< T >::operator[] (const difference_type & i) const
The array subscript operator dereferences this device_ptr by the given index.
Parameters:
i The index to add to this device_ptr's raw pointer before deference.
Returns:
A device_reference referring to the object pointed to by (this device_ptr plus i).
template<typename T> __host__ __device__ reference komrade::device_ptr< T >::operator* (void) const
This method dereferences this device_ptr.
Returns:
a device_reference referring to the object pointed to by this device_ptr.
template<typename T> __host__ __device__ value_type* komrade::device_ptr< T >::get (void) const [inline]
This method returns this device_ptr's raw pointer.
Returns:
This device_ptr's raw pointer.
The documentation for this struct was generated from the following file:
device_ptr.h